brew "curl"
brew "emojify"
brew "gibo"
brew "git-secrets"
brew "git"
{{ if eq .chezmoi.os "linux" }}
{{   if (.chezmoi.kernel.osrelease | lower | contains "microsoft") }}
brew "emacs"
{{   end }}
{{ end }}
