[tools]
# language
node = "lts"
deno = "latest"
# python = "latest"
# go = "latest"
# ruby = "latest"
# rust = "latest"
bun = "latest"

# cli
jq = "latest"
# tmux = "latest"
ripgrep = "latest"
bat = "latest"
coreutils = "latest"
ctop = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
eza = "latest"
# shellcheck = "latest"
# terraform = "latest"
1password = "latest"
lazygit = "latest"
starship = "latest"
# uv = "latest"
# duckdb = "latest"
